# Generated by Django 6.0.3 on 2026-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('customer_id', models.TextField(db_column='Customer ID', primary_key=True, serialize=False)),
                ('customer_name', models.TextField(db_column='Customer Name')),
                ('address', models.TextField(db_column='Address')),
                ('city', models.TextField(db_column='City')),
                ('province', models.TextField(db_column='Province')),
                ('postal_code', models.TextField(db_column='Postal Code')),
                ('region', models.TextField(db_column='Region')),
            ],
            options={
                'db_table': 'Customer List',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RunSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.TextField(blank=True, db_column='Customer ID', null=True)),
                ('order_number', models.CharField(blank=True, default='W', max_length=20, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('line_items', models.IntegerField(blank=True, default=0, null=True)),
                ('customer_name', models.TextField(blank=True, db_column='Customer Name', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
                ('skids', models.IntegerField(blank=True, db_column='Skids', null=True)),
                ('bundles', models.IntegerField(blank=True, db_column='Bundles', null=True)),
                ('coils', models.IntegerField(blank=True, db_column='Coils', null=True)),
                ('closing_time', models.TextField(blank=True, db_column='Closing Time', null=True)),
            ],
            options={
                'db_table': 'Run Sheet',
                'managed': True,
            },
        ),
    ]
