# Generated by Django 6.0.3 on 2026-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_runsheet_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsheet',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
