# Generated by Django 6.0.3 on 2026-04-02 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_runsheet_is_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='runsheet',
            name='line_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runsheet',
            name='order_number',
            field=models.CharField(default='W', max_length=20),
        ),
    ]
