# Generated by Django 6.0.3 on 2026-04-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_runsheet_created_at_alter_runsheet_line_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_name', models.TextField()),
                ('prepared_by', models.CharField(max_length=100)),
                ('line_items', models.IntegerField(default=0)),
                ('skids', models.IntegerField(default=0)),
                ('bundles', models.IntegerField(default=0)),
                ('coils', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('is_tallied', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Order Archive',
            },
        ),
    ]
