# Generated by Django 6.0.3 on 2026-04-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedRunSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('order_numbers', models.TextField()),
                ('weight', models.IntegerField(default=0)),
                ('skids', models.IntegerField(default=0)),
                ('bundles', models.IntegerField(default=0)),
                ('coils', models.IntegerField(default=0)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Finalized Run Sheets',
            },
        ),
    ]
