# Generated by Django 6.0.3 on 2026-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_finalizedrunsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlist',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
