# Generated by Django 6.0.3 on 2026-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customerlist_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderarchive',
            name='bar_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='bar_prep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='covering_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='covering_prep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='sheet_lines',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderarchive',
            name='sheet_prep',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
