# Generated by Django 6.0.3 on 2026-04-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderarchive_bar_lines_orderarchive_bar_prep_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finalizedrunsheet',
            table='finalized_run_sheets',
        ),
    ]
