# Generated by Django 6.0.3 on 2026-04-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_container_containerphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(choices=[('TRUCK_1', 'Truck 1'), ('TRUCK_2', 'Truck 2'), ('LOCAL_1', 'Local 1'), ('LOCAL_2', 'Local 2'), ('OUT_OF_TOWN', 'Out of Town')], max_length=50)),
                ('date_loaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='outbound_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.outboundload')),
            ],
        ),
    ]
