# Generated by Django 6.0.3 on 2026-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_runsheet_postal_code_alter_outboundload_truck_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runsheet',
            options={},
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='address',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='bundles',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='city',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='coils',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='is_pickup',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='region',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='skids',
        ),
        migrations.RemoveField(
            model_name='runsheet',
            name='weight',
        ),
        migrations.AddField(
            model_name='runsheet',
            name='load_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='runsheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='runsheet',
            table=None,
        ),
    ]
