# Generated by Django 6.0.3 on 2026-04-22 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_runsheet_options_remove_runsheet_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runsheet',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='runsheet',
            name='address',
            field=models.TextField(blank=True, db_column='Address', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='bundles',
            field=models.IntegerField(blank=True, db_column='Bundles', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='city',
            field=models.TextField(blank=True, db_column='City', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='closing_time',
            field=models.TextField(blank=True, db_column='Closing Time', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='coils',
            field=models.IntegerField(blank=True, db_column='Coils', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='customer_id',
            field=models.TextField(blank=True, db_column='Customer ID', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='customer_name',
            field=models.TextField(blank=True, db_column='Customer Name', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='line_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='order_number',
            field=models.CharField(default='W', max_length=20),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='region',
            field=models.TextField(blank=True, db_column='Region', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='skids',
            field=models.IntegerField(blank=True, db_column='Skids', null=True),
        ),
        migrations.AddField(
            model_name='runsheet',
            name='weight',
            field=models.IntegerField(blank=True, db_column='Weight', null=True),
        ),
        migrations.AlterField(
            model_name='runsheet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='runsheet',
            table='Run Sheet',
        ),
    ]
