# Generated by Django 6.0.3 on 2026-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_runsheet_options_runsheet_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='runsheet',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
