# Generated by Django 6.0.3 on 2026-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vendor_runsheet_is_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=50)),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('weight', models.IntegerField(default=0)),
                ('skids', models.IntegerField(default=0)),
                ('bundles', models.IntegerField(default=0)),
                ('coils', models.IntegerField(default=0)),
                ('bar_lines', models.IntegerField(default=0)),
                ('sheet_lines', models.IntegerField(default=0)),
                ('covering_lines', models.IntegerField(default=0)),
                ('bar_prep', models.CharField(blank=True, max_length=255)),
                ('sheet_prep', models.CharField(blank=True, max_length=255)),
                ('covering_prep', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
