# Generated by Django 6.0.3 on 2026-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pickuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplog',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
