import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0018_pickupphotolog_pickupphoto",
        ),
        (
            "core",
            "0011_transport_start_time",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "uploaded_by",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "warehouse_20_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "warehouse_21_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "remarks_filename",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),

        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        max_length=10
                    ),
                ),
                (
                    "log_number",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "bin_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "available_pieces",
                    models.IntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "available_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "on_hand_pieces",
                    models.IntegerField(
                        blank=True,
                        null=True,
                    ),
                ),
                (
                    "on_hand_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=(
                            django.db.models
                            .deletion.CASCADE
                        ),
                        related_name="items",
                        to="core.inventoryreport",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "log_number",
                    "warehouse",
                    "bin_location",
                    "id",
                ],
            },
        ),

        migrations.CreateModel(
            name="HymusTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        blank=True,
                        max_length=10,
                    ),
                ),
                (
                    "log_number",
                    models.CharField(
                        max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "bin_location",
                    models.CharField(
                        blank=True,
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True
                    ),
                ),
                (
                    "added_by",
                    models.CharField(
                        blank=True,
                        max_length=150,
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True
                    ),
                ),
            ],
            options={
                "ordering": [
                    "added_at",
                    "id",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "warehouse",
                            "log_number",
                            "bin_location",
                        ),
                        name=(
                            "unique_hymus_transfer_"
                            "inventory_location"
                        ),
                    ),
                ],
            },
        ),
    ]