from io import BytesIO

from django.contrib.auth.decorators import login_required

from openpyxl import load_workbook

from .models import RunSheet
from . import views as base_views


def _metadata_col_for_block(block):
    # Existing layout uses AA/AB hidden columns under hidden_ids_col.
    # Future layout may rename this to customer_code_col.
    return block.get("customer_code_col") or block.get("hidden_ids_col")


def _customer_code_for_stop(stop):
    ids = stop.get("ids") or []
    if not ids:
        return ""

    try:
        first_id = int(ids[0])
    except (TypeError, ValueError):
        return ""

    order = RunSheet.objects.filter(id=first_id).only("customer_id").first()
    return order.customer_id if order else ""


def _inject_customer_codes(workbook, shipping_date):
    """
    Keeps the existing transport Excel layout exactly as generated by views.export_run_sheet_excel,
    but replaces the hidden AA/AB row metadata with customer codes instead of RunSheet row IDs.

    The codes remain outside the visible/printable A:S area. They are only used later by the
    transport import matcher.
    """
    for ws in workbook.worksheets:
        for region, block in base_views.TRANSPORT_REGION_BLOCKS.items():
            metadata_col = _metadata_col_for_block(block)
            if not metadata_col:
                continue

            stops = base_views.build_transport_stops_for_region(region, shipping_date)

            # Clear all metadata cells in the block first so stale values cannot remain behind.
            for row_num in range(block["start_row"], block["end_row"] + 1):
                ws.cell(row=row_num, column=metadata_col).value = None

            # Write customer codes in the same visible order as the original export.
            for index, stop in enumerate(stops):
                row_num = block["start_row"] + index
                if row_num > block["end_row"]:
                    break
                ws.cell(row=row_num, column=metadata_col).value = _customer_code_for_stop(stop)

    # Keep the metadata hidden and outside the printable area.
    for ws in workbook.worksheets:
        ws.column_dimensions["AA"].hidden = True
        ws.column_dimensions["AB"].hidden = True
        ws.print_area = "A1:S75"


@login_required
def export_run_sheet_excel(request):
    """
    Wrapper around the original Excel export.

    It preserves the existing generated workbook/layout, then injects hidden customer codes
    into AA/AB so transport imports can match by customer code instead of fragile row IDs.
    """
    shipping_date = base_views.get_selected_shipping_date(request)
    response = base_views.export_run_sheet_excel(request)

    workbook = load_workbook(BytesIO(response.content))
    _inject_customer_codes(workbook, shipping_date)

    output = BytesIO()
    workbook.save(output)
    output.seek(0)

    response.content = output.getvalue()
    return response
